name: "dhis2: cypress tests"

on: [push]

env:
  CI: true

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          start: 'yarn start'
          wait-on: 'http://localhost:3000'
          wait-on-timeout: 60
          env:
            REACT_APP_DHIS2_BASE_URL: 'https://debug.dhis2.org/2.34dev/'
            REACT_APP_DHIS2_AUTHORIZATION: 'Basic c3lzdGVtOlN5c3RlbTEyMw=='
            REACT_APP_TRACKER_CAPTURE_APP_PATH: 'https://debug.dhis2.org/2.34dev/dhis-web-tracker-capture'

      - name: Upload artifacts
        if: failure()
        uses: actions/upload-artifact@v1
        with:
          name: failed-screenshots
          path: cypress/screenshots


