name: "dhis2: cypress tests"

on: [push]
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          start: 'yarn start'
          wait-on: 'http://localhost:3000'
          wait-on-timeout: 60

      - name: Upload artifacts
        if: failure()
        uses: actions/upload-artifact@v1
        with:
          name: failed-screenshots
          path: cypress/screenshots

    env:
      CI: true
