name: 'dhis2: '

on: push

jobs:
    e2e-test:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v1
              with:
                  node-version: 12.x

            - name: Install
              run: yarn install --frozen-lockfile

            - name: Test
              run: |
                  yarn cy:run
            - name: Upload screenshots
              uses: actions/upload-artifact@v1
              with:
                name: failed-tests.csv
                path: cypress/screenshots
        env:
            CI: true